-- Create pix_transactions table for tracking PIX payments from Buck API
-- This table stores transactions BEFORE they are paid (status: pending)
-- After payment, records are created in the 'payments' table

CREATE TABLE IF NOT EXISTS pix_transactions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  external_id TEXT UNIQUE NOT NULL,
  transaction_id TEXT,
  email TEXT NOT NULL,
  name TEXT NOT NULL,
  amount_cents INTEGER NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'failed', 'expired')),
  tracking JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  paid_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_pix_transactions_external_id ON pix_transactions(external_id);
CREATE INDEX IF NOT EXISTS idx_pix_transactions_transaction_id ON pix_transactions(transaction_id);
CREATE INDEX IF NOT EXISTS idx_pix_transactions_email ON pix_transactions(email);
CREATE INDEX IF NOT EXISTS idx_pix_transactions_status ON pix_transactions(status);
CREATE INDEX IF NOT EXISTS idx_pix_transactions_created_at ON pix_transactions(created_at DESC);

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_pix_transactions_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to call the function before update
DROP TRIGGER IF EXISTS update_pix_transactions_timestamp ON pix_transactions;
CREATE TRIGGER update_pix_transactions_timestamp
  BEFORE UPDATE ON pix_transactions
  FOR EACH ROW
  EXECUTE FUNCTION update_pix_transactions_updated_at();

-- Add comment to table
COMMENT ON TABLE pix_transactions IS 'Tracks PIX payment transactions from Buck API before completion';
COMMENT ON COLUMN pix_transactions.external_id IS 'Unique external ID generated by frontend (quiz-{timestamp}-{random})';
COMMENT ON COLUMN pix_transactions.transaction_id IS 'Buck API transaction ID';
COMMENT ON COLUMN pix_transactions.status IS 'Transaction status: pending, paid, failed, or expired';
COMMENT ON COLUMN pix_transactions.tracking IS 'UTM parameters and tracking data from frontend';
